import { Pickaxe, SquareSquare } from "lucide-react"

export type DataTableConfig = typeof dataTableConfig

export const dataTableConfig = {
  featureFlags: [
    {
      label: "Advanced table",
      value: "advancedTable" as const,
      icon: Pickaxe,
      tooltipTitle: "Toggle advanced table",
      tooltipDescription: "A filter and sort builder to filter and sort rows.",
    },
    {
      label: "Floating bar",
      value: "floatingBar" as const,
      icon: SquareSquare,
      tooltipTitle: "Toggle floating bar",
      tooltipDescription: "A floating bar that sticks to the top of the table.",
    },
  ],
  columnTypes: [
    "text",
    "number",
    "select",
    "multi-select",
    "boolean",
    "date",
  ] as const,
  operators: {
    text: [
      { label: "Contains", value: "contains" as const },
      { label: "Does not contain", value: "not-contains" as const },
      { label: "Equals", value: "equals" as const },
      { label: "Not equals", value: "not-equals" as const },
      { label: "Is empty", value: "is-empty" as const },
      { label: "Is not empty", value: "is-not-empty" as const },
    ],
    number: [
      { label: "Equals", value: "equals" as const },
      { label: "Not equals", value: "not-equals" as const },
      { label: "Less than", value: "less-than" as const },
      { label: "Less than or equals", value: "less-than-or-equals" as const },
      { label: "Greater than", value: "greater-than" as const },
      { label: "Greater than or equals", value: "greater-than-or-equals" as const },
      { label: "Is empty", value: "is-empty" as const },
      { label: "Is not empty", value: "is-not-empty" as const },
    ],
    date: [
      { label: "Equals", value: "equals" as const },
      { label: "Not equals", value: "not-equals" as const },
      { label: "Before", value: "less-than" as const },
      { label: "After", value: "greater-than" as const },
      { label: "On or before", value: "less-than-or-equals" as const },
      { label: "On or after", value: "greater-than-or-equals" as const },
      { label: "Between", value: "between" as const },
      { label: "Not between", value: "not-between" as const },
      { label: "Is today", value: "is-today" as const },
      { label: "Is tomorrow", value: "is-tomorrow" as const },
      { label: "Is next 7 days", value: "is-next-7-days" as const },
      { label: "Is empty", value: "is-empty" as const },
      { label: "Is not empty", value: "is-not-empty" as const },
    ],
    select: [
      { label: "Equals", value: "equals" as const },
      { label: "Not equals", value: "not-equals" as const },
      { label: "In", value: "in" as const },
      { label: "Not in", value: "not-in" as const },
      { label: "Is empty", value: "is-empty" as const },
      { label: "Is not empty", value: "is-not-empty" as const },
    ],
    "multi-select": [
      { label: "Equals", value: "equals" as const },
      { label: "Not equals", value: "not-equals" as const },
      { label: "In", value: "in" as const },
      { label: "Not in", value: "not-in" as const },
      { label: "Is empty", value: "is-empty" as const },
      { label: "Is not empty", value: "is-not-empty" as const },
    ],
    boolean: [
      { label: "Is", value: "equals" as const },
      { label: "Is not", value: "not-equals" as const },
    ],
  },
  globalOperators: [
    "equals",
    "not-equals",
    "contains",
    "not-contains",
    "greater-than",
    "greater-than-or-equals",
    "less-than",
    "less-than-or-equals",
    "in",
    "not-in",
    "between",
    "not-between",
    "is-empty",
    "is-not-empty",
    "is-today",
    "is-tomorrow",
    "is-next-7-days",
  ] as const,
  joinOperators: [
    { label: "And", value: "and" as const },
    { label: "Or", value: "or" as const },
  ],
  sortOrders: [
    { label: "Asc", value: "asc" as const },
    { label: "Desc", value: "desc" as const },
  ],
} as const