/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { db } from ".";
import { createTRPCRouter } from "../../trpc";
import { procedure } from "../../trpc";
import * as _Schema from '@zenstackhq/runtime/zod/input';
const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;
import { checkRead, checkMutate } from '../helper';

export default function createRouter() {
    return createTRPCRouter({

        aggregate: procedure.input($Schema.AllergyInputSchema.aggregate).query(({ ctx, input }) => checkRead(db(ctx).allergy.aggregate(input as any))),

        createMany: procedure.input($Schema.AllergyInputSchema.createMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).allergy.createMany(input as any))),

        create: procedure.input($Schema.AllergyInputSchema.create).mutation(async ({ ctx, input }) => checkMutate(db(ctx).allergy.create(input as any))),

        deleteMany: procedure.input($Schema.AllergyInputSchema.deleteMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).allergy.deleteMany(input as any))),

        delete: procedure.input($Schema.AllergyInputSchema.delete).mutation(async ({ ctx, input }) => checkMutate(db(ctx).allergy.delete(input as any))),

        findFirst: procedure.input($Schema.AllergyInputSchema.findFirst.optional()).query(({ ctx, input }) => checkRead(db(ctx).allergy.findFirst(input as any))),

        findFirstOrThrow: procedure.input($Schema.AllergyInputSchema.findFirst.optional()).query(({ ctx, input }) => checkRead(db(ctx).allergy.findFirstOrThrow(input as any))),

        findMany: procedure.input($Schema.AllergyInputSchema.findMany.optional()).query(({ ctx, input }) => checkRead(db(ctx).allergy.findMany(input as any))),

        findUnique: procedure.input($Schema.AllergyInputSchema.findUnique).query(({ ctx, input }) => checkRead(db(ctx).allergy.findUnique(input as any))),

        findUniqueOrThrow: procedure.input($Schema.AllergyInputSchema.findUnique).query(({ ctx, input }) => checkRead(db(ctx).allergy.findUniqueOrThrow(input as any))),

        groupBy: procedure.input($Schema.AllergyInputSchema.groupBy).query(({ ctx, input }) => checkRead(db(ctx).allergy.groupBy(input as any))),

        updateMany: procedure.input($Schema.AllergyInputSchema.updateMany).mutation(async ({ ctx, input }) => checkMutate(db(ctx).allergy.updateMany(input as any))),

        update: procedure.input($Schema.AllergyInputSchema.update).mutation(async ({ ctx, input }) => checkMutate(db(ctx).allergy.update(input as any))),

        upsert: procedure.input($Schema.AllergyInputSchema.upsert).mutation(async ({ ctx, input }) => checkMutate(db(ctx).allergy.upsert(input as any))),

        count: procedure.input($Schema.AllergyInputSchema.count.optional()).query(({ ctx, input }) => checkRead(db(ctx).allergy.count(input as any))),

    }
    );
}
