/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { AnyTRPCRouter as AnyRouter } from "@trpc/server";
import type { PrismaClient } from "@prisma/client";
import { createTRPCRouter } from "../../trpc";
import createPostRouter from "./Post.router";
import createUserRouter from "./User.router";
import createSessionRouter from "./Session.router";
import createAccountRouter from "./Account.router";
import createVerificationRouter from "./Verification.router";

export function db(ctx: any) {
    if (!ctx.prisma) {
        throw new Error('Missing "prisma" field in trpc context');
    }
    return ctx.prisma as PrismaClient;
}

export function createRouter() {
    return createTRPCRouter({
        post: createPostRouter(),
        user: createUserRouter(),
        session: createSessionRouter(),
        account: createAccountRouter(),
        verification: createVerificationRouter(),
    }
    );
}
