/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { db } from ".";
import { createTRPCRouter } from "../../trpc";
import { procedure } from "../../trpc";
import * as _Schema from '@zenstackhq/runtime/zod/input';
const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;
import { checkRead, checkMutate } from '../helper';

export default function createRouter() {
    return createTRPCRouter({

        aggregate: procedure.input($Schema.PatientAllergyInputSchema.aggregate).query(({ ctx, input }) => checkRead(db(ctx).patientAllergy.aggregate(input as any))),

        createMany: procedure.input($Schema.PatientAllergyInputSchema.createMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).patientAllergy.createMany(input as any))),

        create: procedure.input($Schema.PatientAllergyInputSchema.create).mutation(async ({ ctx, input }) => checkMutate(db(ctx).patientAllergy.create(input as any))),

        deleteMany: procedure.input($Schema.PatientAllergyInputSchema.deleteMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).patientAllergy.deleteMany(input as any))),

        delete: procedure.input($Schema.PatientAllergyInputSchema.delete).mutation(async ({ ctx, input }) => checkMutate(db(ctx).patientAllergy.delete(input as any))),

        findFirst: procedure.input($Schema.PatientAllergyInputSchema.findFirst.optional()).query(({ ctx, input }) => checkRead(db(ctx).patientAllergy.findFirst(input as any))),

        findFirstOrThrow: procedure.input($Schema.PatientAllergyInputSchema.findFirst.optional()).query(({ ctx, input }) => checkRead(db(ctx).patientAllergy.findFirstOrThrow(input as any))),

        findMany: procedure.input($Schema.PatientAllergyInputSchema.findMany.optional()).query(({ ctx, input }) => checkRead(db(ctx).patientAllergy.findMany(input as any))),

        findUnique: procedure.input($Schema.PatientAllergyInputSchema.findUnique).query(({ ctx, input }) => checkRead(db(ctx).patientAllergy.findUnique(input as any))),

        findUniqueOrThrow: procedure.input($Schema.PatientAllergyInputSchema.findUnique).query(({ ctx, input }) => checkRead(db(ctx).patientAllergy.findUniqueOrThrow(input as any))),

        groupBy: procedure.input($Schema.PatientAllergyInputSchema.groupBy).query(({ ctx, input }) => checkRead(db(ctx).patientAllergy.groupBy(input as any))),

        updateMany: procedure.input($Schema.PatientAllergyInputSchema.updateMany).mutation(async ({ ctx, input }) => checkMutate(db(ctx).patientAllergy.updateMany(input as any))),

        update: procedure.input($Schema.PatientAllergyInputSchema.update).mutation(async ({ ctx, input }) => checkMutate(db(ctx).patientAllergy.update(input as any))),

        upsert: procedure.input($Schema.PatientAllergyInputSchema.upsert).mutation(async ({ ctx, input }) => checkMutate(db(ctx).patientAllergy.upsert(input as any))),

        count: procedure.input($Schema.PatientAllergyInputSchema.count.optional()).query(({ ctx, input }) => checkRead(db(ctx).patientAllergy.count(input as any))),

    }
    );
}
