/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { db } from ".";
import { createTRPCRouter } from "../../trpc";
import { procedure } from "../../trpc";
import * as _Schema from '@zenstackhq/runtime/zod/input';
const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;
import { checkRead, checkMutate } from '../helper';

export default function createRouter() {
    return createTRPCRouter({

        aggregate: procedure.input($Schema.VaccinationValuesInputSchema.aggregate).query(({ ctx, input }) => checkRead(db(ctx).vaccinationValues.aggregate(input as any))),

        createMany: procedure.input($Schema.VaccinationValuesInputSchema.createMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).vaccinationValues.createMany(input as any))),

        create: procedure.input($Schema.VaccinationValuesInputSchema.create).mutation(async ({ ctx, input }) => checkMutate(db(ctx).vaccinationValues.create(input as any))),

        deleteMany: procedure.input($Schema.VaccinationValuesInputSchema.deleteMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).vaccinationValues.deleteMany(input as any))),

        delete: procedure.input($Schema.VaccinationValuesInputSchema.delete).mutation(async ({ ctx, input }) => checkMutate(db(ctx).vaccinationValues.delete(input as any))),

        findFirst: procedure.input($Schema.VaccinationValuesInputSchema.findFirst.optional()).query(({ ctx, input }) => checkRead(db(ctx).vaccinationValues.findFirst(input as any))),

        findFirstOrThrow: procedure.input($Schema.VaccinationValuesInputSchema.findFirst.optional()).query(({ ctx, input }) => checkRead(db(ctx).vaccinationValues.findFirstOrThrow(input as any))),

        findMany: procedure.input($Schema.VaccinationValuesInputSchema.findMany.optional()).query(({ ctx, input }) => checkRead(db(ctx).vaccinationValues.findMany(input as any))),

        findUnique: procedure.input($Schema.VaccinationValuesInputSchema.findUnique).query(({ ctx, input }) => checkRead(db(ctx).vaccinationValues.findUnique(input as any))),

        findUniqueOrThrow: procedure.input($Schema.VaccinationValuesInputSchema.findUnique).query(({ ctx, input }) => checkRead(db(ctx).vaccinationValues.findUniqueOrThrow(input as any))),

        groupBy: procedure.input($Schema.VaccinationValuesInputSchema.groupBy).query(({ ctx, input }) => checkRead(db(ctx).vaccinationValues.groupBy(input as any))),

        updateMany: procedure.input($Schema.VaccinationValuesInputSchema.updateMany).mutation(async ({ ctx, input }) => checkMutate(db(ctx).vaccinationValues.updateMany(input as any))),

        update: procedure.input($Schema.VaccinationValuesInputSchema.update).mutation(async ({ ctx, input }) => checkMutate(db(ctx).vaccinationValues.update(input as any))),

        upsert: procedure.input($Schema.VaccinationValuesInputSchema.upsert).mutation(async ({ ctx, input }) => checkMutate(db(ctx).vaccinationValues.upsert(input as any))),

        count: procedure.input($Schema.VaccinationValuesInputSchema.count.optional()).query(({ ctx, input }) => checkRead(db(ctx).vaccinationValues.count(input as any))),

    }
    );
}
