/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { db } from ".";
import { createTRPCRouter } from "../../trpc";
import { procedure } from "../../trpc";
import * as _Schema from '@zenstackhq/runtime/zod/input';
const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;
import { checkRead, checkMutate } from '../helper';

export default function createRouter() {
    return createTRPCRouter({

        aggregate: procedure.input($Schema.VaccinationInputSchema.aggregate).query(({ ctx, input }) => checkRead(db(ctx).vaccination.aggregate(input as any))),

        createMany: procedure.input($Schema.VaccinationInputSchema.createMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).vaccination.createMany(input as any))),

        create: procedure.input($Schema.VaccinationInputSchema.create).mutation(async ({ ctx, input }) => checkMutate(db(ctx).vaccination.create(input as any))),

        deleteMany: procedure.input($Schema.VaccinationInputSchema.deleteMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).vaccination.deleteMany(input as any))),

        delete: procedure.input($Schema.VaccinationInputSchema.delete).mutation(async ({ ctx, input }) => checkMutate(db(ctx).vaccination.delete(input as any))),

        findFirst: procedure.input($Schema.VaccinationInputSchema.findFirst.optional()).query(({ ctx, input }) => checkRead(db(ctx).vaccination.findFirst(input as any))),

        findFirstOrThrow: procedure.input($Schema.VaccinationInputSchema.findFirst.optional()).query(({ ctx, input }) => checkRead(db(ctx).vaccination.findFirstOrThrow(input as any))),

        findMany: procedure.input($Schema.VaccinationInputSchema.findMany.optional()).query(({ ctx, input }) => checkRead(db(ctx).vaccination.findMany(input as any))),

        findUnique: procedure.input($Schema.VaccinationInputSchema.findUnique).query(({ ctx, input }) => checkRead(db(ctx).vaccination.findUnique(input as any))),

        findUniqueOrThrow: procedure.input($Schema.VaccinationInputSchema.findUnique).query(({ ctx, input }) => checkRead(db(ctx).vaccination.findUniqueOrThrow(input as any))),

        groupBy: procedure.input($Schema.VaccinationInputSchema.groupBy).query(({ ctx, input }) => checkRead(db(ctx).vaccination.groupBy(input as any))),

        updateMany: procedure.input($Schema.VaccinationInputSchema.updateMany).mutation(async ({ ctx, input }) => checkMutate(db(ctx).vaccination.updateMany(input as any))),

        update: procedure.input($Schema.VaccinationInputSchema.update).mutation(async ({ ctx, input }) => checkMutate(db(ctx).vaccination.update(input as any))),

        upsert: procedure.input($Schema.VaccinationInputSchema.upsert).mutation(async ({ ctx, input }) => checkMutate(db(ctx).vaccination.upsert(input as any))),

        count: procedure.input($Schema.VaccinationInputSchema.count.optional()).query(({ ctx, input }) => checkRead(db(ctx).vaccination.count(input as any))),

    }
    );
}
